### ISSUE TITLE
Ability to automatically take picture?

### ISSUE THREAD

**Issue by marbetschar** [mmackh/IPDFCameraViewController#41]
Is there a possibility to get this library automatically taking a picture as soon as it recognizes a document?

**Comment by mmackh** [comment]
Yes, this is possible. However, due to this library being copied into scanner apps without any/little modifications I decided against open sourcing InstaPDF's for of this library. I implemented it like so:

1. Create a threshold value
2. Keep reference to previously detected rectangle
3. Compare the previously detected rectangle, where each point is within a valid range (~50px)
4. Once you detect a certain amount of valid rectangles you can auto capture.

Hope this helps.
